### ISSUE TITLE
INVALID: invalid distance too far back

### ISSUE THREAD

**Issue by ubaldiniTerre** [lucadentella/raspberry-dgc#1]
Hy, 

i'm trying the server on my local WSL2 ubuntu installation as a standalone, I do get to run it and It takes my personal (and valid)  greenpass QR code string value, like in the example, but i responds always: 

**INVALID: invalid distance too far back**

I don't understand why.

my stack:
```
nodejs: 12.14.1
nom: 6.13.4

node_modules: {
  validatorserver: '0.0.1',
  npm: '6.14.15',
  ares: '1.17.2',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.6',
  openssl: '1.1.1l',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.76',
  zlib: '1.2.11'
}
```

also, which version of NodeJS are you using?

**Comment by lucadentella** [comment]
Hi, did you solve your problem?
