### ISSUE TITLE
Installazione infinita

### ISSUE THREAD

**Issue by matly006** [lucadentella/raspberry-dgc#14]
Luca salve, sto tentando di installate il tuo software su un raspberry 2b. Eseguo tutti i passaggi fino al momento in cui lancio il comando: pip3 install opencv-contrib-python zbarlight

il processo è attivo per piu di 7 ore consegutive senza vedere la fine, la cpu è utilizzata al 100% dal processo "ccplus":

Installing collected packages: opencv-contrib-python
  Running setup.py install for opencv-contrib-python ... /

grazie

**Comment by lucadentella** [comment]
@matly006 il problema è stato risolto?

**Comment by lucadentella** [comment]
nessun ulteriore aggiornamento, chiudo
