### ISSUE TITLE
libqtgui4 is not available

### ISSUE THREAD

**Issue by pol-hallen** [lucadentella/raspberry-dgc#16]
missed package on debian :-/ 

Is there a way to use other gui packages?

package libqtgui4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by lucadentella** [comment]
Hi

you probably don't need it: if it's not available in your distro, the package manager should be smart enough to solve the dependencies for the main package (python) automatically.

**Comment by pol-hallen** [comment]
following your docs, missed the command npm:  npm: command not found

4. Install NodeJS libraries

cd validatorServer
npm install

**Comment by lucadentella** [comment]
Hi, did you solve?

**Comment by pol-hallen** [comment]
Yep Luca, thanks!
