### ISSUE TITLE
browser client and raspberry pi camera

### ISSUE THREAD

**Issue by colanfab** [lucadentella/raspberry-dgc#17]
The browserClient work well with an image file but when I try to use the pi camera the client doesn't recognize it.
When I click "Request camera permission" it send a "NotFoubndError: Requested device not Found"
If I try with a computer camera it works
The pi camera works if I use the cameraClient.py
What can I check ?

**Comment by lucadentella** [comment]
please note that browserClient uses the camera connected to the PC where you run the browser, not the camera connected to the server. Are you running the browser on Raspberry or on a different computer? If the latter, connect a webcam to that computer and you'll be able to use the browserClient.

**Comment by colanfab** [comment]
Ok thanks.
I tried to use different computer and the cam works correctly. I tried pc, iMac, ios etc.
So we can't use the browser on raspberry but only the cameraClient.
