### ISSUE TITLE
Rpi camera resolution

### ISSUE THREAD

**Issue by micBona** [lucadentella/raspberry-dgc#2]
Hello Luca, which type of rpi camera are you using? 
I'm testing your code with a RPI 3B+ and a rpi camera V2 with 5MP. It works well with small qr codes but it cannot detect the green pass from a mobile phone.
It works with the green pass only if it is large enough (e.g. 10 cm x 10 cm).
Do you have any suggestions? 
Thank you in advance.

**Comment by lucadentella** [comment]
Hi

I'm using an old pi camera v1.3 and I was able to detect qr codes on my mobile phone screen (as you can see in the youtube video). 
With you camera, you may try to increase the resolution used by cameraClient... it will probably slow down the process a bit but it should help:
https://github.com/lucadentella/raspberry-dgc/blob/7290a2fbf7138f772ddb2cd0e6b41c0e2ed19bdb/cameraClient/cameraClient.py#L22

**Comment by lucadentella** [comment]
in addition: if you uncomment the following two lines:

https://github.com/lucadentella/raspberry-dgc/blob/7290a2fbf7138f772ddb2cd0e6b41c0e2ed19bdb/cameraClient/cameraClient.py#L34

https://github.com/lucadentella/raspberry-dgc/blob/7290a2fbf7138f772ddb2cd0e6b41c0e2ed19bdb/cameraClient/cameraClient.py#L67

and you use a terminal with x-server functionality (like MobaXterm) you can "see" what the camera is framing

**Comment by micBona** [comment]
Thank you. I have increase the resulution to 720x480 and everything is working fine now.
I have another question, how frequently are the signature and the business updated? and how is it performed?

**Comment by lucadentella** [comment]
Hi! Glad you solved, I'll update the documentation.

At the moment certificates and settings are updated only at startup... I've a working code to update them periodically ready to be committed.

**Comment by micBona** [comment]
Great!! I'll await your commit. 
Thanks again.

**Comment by lucadentella** [comment]
In release **2.0.0** you can set the update frequency (see [FAQ](https://github.com/lucadentella/raspberry-dgc/blob/main/documentation/faq.md)).
