### ISSUE TITLE
Problem with install opencv-contrib-python

### ISSUE THREAD

**Issue by dolphkin** [lucadentella/raspberry-dgc#20]
Ciao Luca,
non so se è il posto giusto per inserire questo problema, ma eseguendo i comandi per installare tutte le librerie e i pacchetti per la tua applicazione sto avendo problemi ad installare opencv-contrib-python.

![Cattura](https://user-images.githubusercontent.com/48755959/141274924-48bda7ee-30d0-4518-a0ae-eca061d0a989.PNG)

ho provato ad installare diverse versioni di opencv-contrib-python:

![Catt](https://user-images.githubusercontent.com/48755959/141275307-14bbdac8-94fc-4505-acb3-31b8ee984bce.PNG)

una volta poi avviato il programma cameraClient.py ricevo questi errori:+

![Catt4](https://user-images.githubusercontent.com/48755959/141275419-d18a9e39-be0e-4d10-a2b9-e44551134be9.PNG)

Senza installarlo riesco a leggere dei qr-code ma con molta difficoltà e per i green-pass dal telefono non li riconosce.
il raspberry che utlizzo è un 3B+ e la fotocamera utilizzata è la pi camera V2.1.
Grazie e complimenti per l'applicazione!

**Comment by lucadentella** [comment]
Ciao

è possibile che ci sia già installata una versione di numpy più vecchia, prova a aggiornarla con

`pip install -U numpy `

**Comment by dolphkin** [comment]
Grazie per la risposta, ho risolto il problema c'era già una versione precedentemente installata
![Cata](https://user-images.githubusercontent.com/48755959/141282207-d28fda7f-6b8f-4ed7-ae53-17c855749e30.PNG)

il greenpass sulla carta ora lo legge bene, mentre sul telefono ho ancora problemi di acquisizione.
Ho già provato ad aumentare la risoluzione ma non riesce a riconoscerli, hai qualche suggerimento?
Ho provato a cercare come mettere a fuoco la camera V2.1 ma non ho trovato nulla...

**Comment by lucadentella** [comment]
https://forums.raspberrypi.com/viewtopic.php?t=182963

configura il client per visualizzare in finestra quello che "vede" la camera e prova ad aggiustare il focus in tal modo: un utente in una issue precedente ha scritto di aver risolto cosi

**Comment by dolphkin** [comment]
Perfetto, sono riuscito! 
Era un problema di messa a fuoco.
Grazie

**Comment by lucadentella** [comment]
bene!
