### ISSUE TITLE
dgc recovery Expired ma ancora valida per VerificaC19

### ISSUE THREAD

**Issue by st4nny** [lucadentella/raspberry-dgc#22]
Ciao,
non ricordo se nel tempo la data di validità di una dgc di tipo recovery è cambiata.
Comunque stante ai settings sono +180gg dal giorno della validità della certificazione.
Mi sono ritrovato con un pdf di una recovery valida dai primi di giugno, sulla carta c'era scritto valida fino ai primi di novembre
ma l'app VerificaC19 la da buona ed in teoria ci starebbe perchè fino a dicembre (+180) sarebbe valida,
mentre in recovery.js vedo che viene valutata certificateValidUntil = obj.du; presa direttamente dal certificato quindi non viene applicata la rules dai settings quindi ci sta che ritornasse Scaduto.

Che dici?

**Comment by lucadentella** [comment]
ciao!

ottimo punto: ho controllato poco fa e pare sia stato cambiato recentemente il comportamento dell'SDK:

https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/blob/0ee82bdcb1a59ecca8583f5689efa0d1353bb92d/sdk/src/main/java/it/ministerodellasalute/verificaC19sdk/model/VerificationViewModel.kt#L479-L505

ora effettivamente si basa sui settings, se vedi è rimasta comunque la riga

`val endDate: LocalDate =
                LocalDate.parse(clearExtraTime(it.last().certificateValidUntil))`

che non viene più utilizzata e che leggeva il valore di end date dal DGC.

Aggiorno anche il mio codice, grazie x la segnalazione!

**Comment by lucadentella** [comment]
Ciao

ho effettuato una PR direttamente sul nuovo SDK che prevedo quanto prima di integrare in questo progetto:
https://github.com/italia/verificac19-sdk/pull/3
