### ISSUE TITLE
Vaccination rules

### ISSUE THREAD

**Issue by mcurtaz** [lucadentella/raspberry-dgc#23]
Hi Luca,
in vaccination.js the end day is dateOfVaccination + vaccine_end_day_not_complete. 

`var endDate = dayjs(dateOfVaccination).add(parseInt(getVaccineEndDayNotComplete(settings, vaccineType).value), 'days');`

I think it should be vaccination_day + vaccine_start_day_not_complete + vaccine_end_day_not_complete.

The **vaccine_start_day_complete** is always 0 so it's not important but in case of first dose it will make a difference.

Thank you for your job!

**Comment by lucadentella** [comment]
you're right, thanks for reporting it! I'm going to fix it ASAP

**Comment by lucadentella** [comment]
Fixed in release **2.0.0**
