### ISSUE TITLE
Validate Swiss greenpass problem

### ISSUE THREAD

**Issue by flagellarmirror** [lucadentella/raspberry-dgc#24]
Hi,
I have a problem with the validity of the greenpass of one of my Swiss employees. When I try to scan his green pass he tells me it is invalid. The server should validate all the greenpass not only the Italian ones, is that correct?

**Comment by lucadentella** [comment]
Hi, it should work: we faced some issues with the key used by swiss dgc but it was solved (see closed issues)
Is it related to the signature validation or to business rules?

**Comment by flagellarmirror** [comment]
Hi, I solved it, in the end it was my fault that I was still using dcc-utils library 0.1.0 and had the old version of cose-js. I have updated the dcc-utils library to version 0.4.0 and everything works fine, thanks a lot.
