### ISSUE TITLE
Invalid base45 string

### ISSUE THREAD

**Issue by andesim** [lucadentella/raspberry-dgc#25]
la funzione qui sotto da sempre come errore Invalid base45 string
se uno gli passa la stringa letta da un QR Code Scanner di un qualsiasi Green Pass valido o meno. 

.........

function onScanSuccess(decodedText, decodedResult) {

	console.log("qrcode found: " + decodedText);
	
	// make a call to validatorServer
	$.ajax({
		url: validatorServerURL,
		type: "get",
		data: {"dgc" : decodedText},
		.....................

perché  ???

**Comment by lucadentella** [comment]
ciao, quella parte di codice è del cameraClient, non ho capito cosa intendi con "passa la stringa letta da un QR Code"... è lui che effettua la scansione.

Se invece stai chiamando direttamente il server (non usando il client Python) controlla di fare la corretta **urlencode** della stinga base45, il problema è normalmente li.

**Comment by andesim** [comment]
la chiamata la facevo tramite postman quindi ti ringrazio hai ragione.
ho provato a cablare il parametro dgc con il QRcode dentro app.js é risponde correttamente Valid

Grazie
