### ISSUE TITLE
Normal or Super

### ISSUE THREAD

**Issue by egrittini-solinfo** [lucadentella/raspberry-dgc#26]
Hi Luca, will you update the code to enable the new verification mode (Normal, Super)?
Thank you for your hard work.

**Comment by lucadentella** [comment]
Hi!

I'm working to include in my project the "almost-official" NodeJS SDK (see #21 ) which should be updated with every new business rule... it should be ready soon!

**Comment by egrittini-solinfo** [comment]
Hi Luca, any update on this?

**Comment by lucadentella** [comment]
Hi

I've just published a new version that leverages the official SDK and also includes the possibility to specify the scan mode.

At the moment it's in a dedicated branch:
https://github.com/lucadentella/raspberry-dgc/tree/feat/official-sdk

Could you try it? 
If you want a "super greenpass" check, just add `scanMode=2G` to the querystring, like:

`http://localhost:3000/?scanMode=2G&dgc=HC1...`

**Comment by lucadentella** [comment]
Release **2.0.0** does include the possibility to ask for a "super dgc" scan, see [FAQ](https://github.com/lucadentella/raspberry-dgc/blob/main/documentation/faq.md)

**Comment by egrittini-solinfo** [comment]
Hi Luca, the new version works like a charm!
Great work! Thank you.

**Comment by lucadentella** [comment]
thanks for reporting!
