### ISSUE TITLE
speed up certificate check

### ISSUE THREAD

**Issue by Robertoanto** [lucadentella/raspberry-dgc#27]
Hi thank you for great work.
I have a little question, the loop for certificate check take from 5 to 15 seconds with 252 certificate, on a PI3
There is a way to speed up certificate check ?

**Comment by lucadentella** [comment]
Hi Roberto,

yes, the new version will compare the KID specified in the greenpass and validate the signature only with that certificate. It dramatically speeds up the check.
At the moment the new version is available in a dedicated branch, if you want to test it:
https://github.com/lucadentella/raspberry-dgc/tree/feat/official-sdk

**Comment by lucadentella** [comment]
Hi Roberto

release 2.0.0 includes the changes I mentioned in my previous comment. Could you please test?

**Comment by Robertoanto** [comment]
Hi, as soon as possible I will do it

**Comment by lucadentella** [comment]
Hi Roberto,

were you able to test the new ver?

**Comment by john307** [comment]
> Hi Roberto,
> 
> yes, the new version will compare the KID specified in the greenpass and validate the signature only with that certificate. It dramatically speeds up the check. At the moment the new version is available in a dedicated branch, if you want to test it: https://github.com/lucadentella/raspberry-dgc/tree/feat/official-sdk

Ciao Luca, la versione che menzioni è in sviluppo o è in versione definitiva? 
grazie!

**Comment by lucadentella** [comment]
Ciao, attualmente è quella definitiva, che sfrutta l'SDK ufficiale e applica la logica dei KID descritta sopra
