### ISSUE TITLE
Nuova versione verificac19-sdk con supporto CRL

### ISSUE THREAD

**Issue by astagi** [lucadentella/raspberry-dgc#29]
Ciao! ho rilasciato la nuova versione, ci sono alcune breaking change oltre che il supporto a MongoDB.

Note di rilascio: https://github.com/italia/verificac19-sdk/releases

Per qualsiasi supporto / richiesta di chiarimento fammi sapere!

**Comment by mirof** [comment]
Ciao, e' possibile che ci siano ancora problemi con le revocation list? 
Proprio Ieri un Green Pass sicuramente revocato per positivita' veniva ancora riconosciuto come valido dal  validatorServer mentre la app VerificaC19 lo rileva come non valido. 
Grazie e complimenti per l'utilissimo progetto!

**Comment by st4nny** [comment]
Se può esserti utile, ti ho fatto una pull request: https://github.com/lucadentella/raspberry-dgc/pull/38
implementando la revoke list, in questo caso proposta ed implementata con sqlite, esiste anche la possibilità di attivarla in lowdb ma sono noti problemi prestazionali su file di media entità. Mi è sembrato che, data la natura del progetto, fosse più adatta rispetto alla versione originale che utilizza giustamente mongo.

Un saluto

**Comment by astagi** [comment]
Grazie @st4nny ho richiesto alcuni cambiamenti :) per il resto direi ottimo, non so se per la natura del progetto forse switchare ad un database come sqlite o un qualche key value ottimizzato per l'embedded possa rendere il tutto più leggero, non ho idea di quanto impatti MongoDB in esecuzione su una RaspberryPi.

**Comment by lucadentella** [comment]
grazie mille per i contributi, ho fatto la merge
