### ISSUE TITLE
zbarlight

### ISSUE THREAD

**Issue by nikyred78** [lucadentella/raspberry-dgc#3]
Ciao Luca,
Ottima guida.

nonostante ho instalalto la libreria zbarlight , quando eseguo il codice python cameraClient.py mi restituisce l'errore che il modulo non c'è.
Hai qualche consiglio?
Grazie

**Comment by lucadentella** [comment]
ciao! 

è possibile che tu l'abbia installata per la versione 3 di python (usando pip3) mentre poi lanci l'interprete python 2.x (usando il comando "python" invece che "python3")?

**Comment by lucadentella** [comment]
Ho il sospetto che manchi nella documentazione l'installazione dei moduli di S.O. (la libreria è un wrapper). Prova a lanciare anche:

`apt-get install libzbar0 libzbar-dev`

**Comment by nikyred78** [comment]
si perfetto è andata , ho installato la libreria con il comando pip3 , dopo di che ho eseguito il file cameraClient.py con il comando python3. Direi Ottimo.
L'unica cosa , come si legge su , effettivamente con la pi camera si hanno un pò di diffioltà nel leggere il QrCode. L'ideale sarebbe che all'avvio del programma si aprisse anche la finestra della Cam . 

Se volessi utilizzare una webcam USB ? il programma pescherebbe dalla Web o è da modificare il file python? Grazie

**Comment by lucadentella** [comment]
se vuoi far aprire la finestra della camera, puoi seguire le istruzioni che ho messo in #2 (si tratta di decommentare due righe). 
per l'uso di cam USB va modificato leggermente il software perché PiCamera [non le supporta](https://picamera.readthedocs.io/en/release-1.13/faq.html#can-i-use-picamera-with-a-usb-webcam).

non dovrebbe essere difficile perché usando CV2 si può sfruttare [la funzionalità built-in](https://raspberrypi-guide.github.io/electronics/using-usb-webcams#controlling-the-webcam-with-python)... non ho però sottomano una webcam USB per fare qualche test.
