### ISSUE TITLE
Error: ENOENT: no such file or directory, open '.cache/crl.json'

### ISSUE THREAD

**Issue by andreapluda** [lucadentella/raspberry-dgc#30]
Ciao Luca, è la prima volta che uso Node.js e non riesco a far funzionare il validatorServer. Ho un raspberry fresco di installazione con RaspiOS lite, ho clonato la repo e installato node.js. Eseguito npm install mi da un un paio di warning su delle dipendenze che non riesco a correggere e avviato app.js mi restituisce:

validatorServer 1.0.0

ADD_HOLDER_DETAILS:  enabled
ADD_DETAILED_MESSAGE:  enabled
Updating keys, settings and blacklist...(node:2448) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.cache/crl.json'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Cache.getCRLStatus (/home/pi/raspberry-dgc/validatorServer/node_modules/verificac19-sdk/src/cache.js:80:37)
    at Cache.needCRLUpdate (/home/pi/raspberry-dgc/validatorServer/node_modules/verificac19-sdk/src/cache.js:63:14)
    at updateCRL (/home/pi/raspberry-dgc/validatorServer/node_modules/verificac19-sdk/src/service.js:31:14)
    at Object.updateAll (/home/pi/raspberry-dgc/validatorServer/node_modules/verificac19-sdk/src/service.js:112:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async update (/home/pi/raspberry-dgc/validatorServer/app.js:17:2)
    at async main (/home/pi/raspberry-dgc/validatorServer/app.js:33:2)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Come ho detto prima, sono un novizio di Node.js e non capisco cosa posso fare per sistemare

EDIT: Ho riprovato tutti i passaggi e ora "npm install" si esegue senza problemi, resta lo stesso problema sull'esecuzione di "node app.js"

**Comment by lucadentella** [comment]
Ciao Andrea

il problema è causato dalla nuova libreria (vedi #29 ), intanto che aggiorno il software ho configurato il package in modo da forzare l'uso della versione 0.5.1. Puoi provare nuovamente? Dovrai cancellare l'intera cartella node_modules e rilanciare npm install (oppure partire proprio da un clone pulito)

fammi sapere

**Comment by AntonioAccess** [comment]
io ho risolto usando le informazioni su https://github.com/italia/verificac19-sdk/releases creando un index.js aggiungendo il require nel app.js e richiamando la funzione await nell'update, non so se cambia in peggio per altro, comunque funziona. grazie

**Comment by andreapluda** [comment]
Risolto installando manualmente verificac19-sdk@0.5.1
