### ISSUE TITLE
problem installing opencv-contrib-python

### ISSUE THREAD

**Issue by TBKRK** [lucadentella/raspberry-dgc#31]
Hi, I try to install on raspberrypi zero, but get following error.
I use --no-cache-dir, without it it fails with "killed" status - probably not enough memory.

pi@raspberrypi:~ $ pip3 install opencv-contrib-python --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-contrib-python
  Downloading https://files.pythonhosted.org/packages/13/71/7d4bf5e4709aa6478718                                                                        7a63810f040d4d3d7ad329b618b0dea013fdb198/opencv-contrib-python-4.5.5.62.tar.gz (                                                                        150.4MB)
    100% |████████████████████████████████| 150.4MB 1.5MB/s
  Installing build dependencies ... done
Requirement already satisfied: numpy>=1.14.5 in /usr/lib/python3/dist-packages (                                                                        from opencv-contrib-python) (1.16.2)
Installing collected packages: opencv-contrib-python
  Running setup.py install for opencv-contrib-python ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, toke                                                                        nize;__file__='/tmp/pip-install-1p75nk67/opencv-contrib-python/setup.py';f=getat                                                                        tr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close                                                                        ();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lu0ga                                                                        6v6/install-record.txt --single-version-externally-managed --compile --user --pr                                                                        efix=:
    /tmp/pip-build-env-84b1vuda/lib/python3.7/site-packages/setuptools/command/i                                                                        nstall.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use                                                                         build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    Traceback (most recent call last):
      File "/tmp/pip-build-env-84b1vuda/lib/python3.7/site-packages/skbuild/setu                                                                        ptools_wrap.py", line 564, in setup
        cmkr = cmaker.CMaker(cmake_executable)
      File "/tmp/pip-build-env-84b1vuda/lib/python3.7/site-packages/skbuild/cmak                                                                        er.py", line 95, in __init__
        self.cmake_version = get_cmake_version(self.cmake_executable)
      File "/tmp/pip-build-env-84b1vuda/lib/python3.7/site-packages/skbuild/cmak                                                                        er.py", line 82, in get_cmake_version
        "Problem with the CMake installation, aborting build. CMake executable i                                                                        s %s" % cmake_executable)

    Problem with the CMake installation, aborting build. CMake executable is cma                                                                        ke

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-                                                                        install-1p75nk67/opencv-contrib-python/setup.py';f=getattr(tokenize, 'open', ope                                                                        n)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __                                                                        file__, 'exec'))" install --record /tmp/pip-record-lu0ga6v6/install-record.txt -                                                                        -single-version-externally-managed --compile --user --prefix=" failed with error                                                                         code 1 in /tmp/pip-install-1p75nk67/opencv-contrib-python/
pi@raspberrypi:~ $ sudo pip3 install opencv-contrib-python --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-contrib-python
  Downloading https://files.pythonhosted.org/packages/13/71/7d4bf5e4709aa64787187a63810f040d4d3d7ad329b618b0dea013fdb198/opencv-contrib-python-4.5.5.62.tar.gz (150.4MB)
    100% |████████████████████████████████| 150.4MB 1.7MB/s
  Installing build dependencies ... done
Requirement already satisfied: numpy>=1.14.5 in /usr/lib/python3/dist-packages (from opencv-contrib-python) (1.16.2)
Installing collected packages: opencv-contrib-python
  Running setup.py install for opencv-contrib-python ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-m1tbgd3p/opencv-contrib-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-32tpc4zn/install-record.txt --single-version-externally-managed --compile:
    /tmp/pip-build-env-v9uo3gw2/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    Traceback (most recent call last):
      File "/tmp/pip-build-env-v9uo3gw2/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 564, in setup
        cmkr = cmaker.CMaker(cmake_executable)
      File "/tmp/pip-build-env-v9uo3gw2/lib/python3.7/site-packages/skbuild/cmaker.py", line 95, in __init__
        self.cmake_version = get_cmake_version(self.cmake_executable)
      File "/tmp/pip-build-env-v9uo3gw2/lib/python3.7/site-packages/skbuild/cmaker.py", line 82, in get_cmake_version
        "Problem with the CMake installation, aborting build. CMake executable is %s" % cmake_executable)

    Problem with the CMake installation, aborting build. CMake executable is cmake

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-m1tbgd3p/opencv-contrib-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-32tpc4zn/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-m1tbgd3p/opencv-contrib-python/

**Comment by lucadentella** [comment]
Hi

OpenCV requires a huge amount of resources and, reading the forum, I can see many users facing similar issues.
Unfortunately this is not something I can solve, you'd better ask in the official forum/repo.

I tested the project with Pi3 (and Pi4) and the installation of OpenCV took several minutes but succeded.

**Comment by TBKRK** [comment]
Hi, thank you for explanation, will try to manage it…

One more question – which version of Raspberry do you use? Bullseye with or without desktop? Or Raspberry Pi OS legacy with or without desktop?

 

Regards

Tomasz
