### ISSUE TITLE
Led pins

### ISSUE THREAD

**Issue by barvela** [lucadentella/raspberry-dgc#32]
Hello,
in the video is not very clear how to connect the two leds to the board pins. Can you please write me down the right connections? Grazie.

**Comment by lucadentella** [comment]
Hi

LEDs are simply connected with + to the pins declared in the client:

https://github.com/lucadentella/raspberry-dgc/blob/3ca0d33d7b71828575cc708e7b203986d1d13558/cameraClient/cameraClient.py#L12-L13

and ground to a gnd pin available in the pi 40-pins connector. I used a 470ohm resistor in series but the value really depends on the leds you choose and the brightness you want.
