### ISSUE TITLE
Problema con Camera client

### ISSUE THREAD

**Issue by AntonioMazzarella** [lucadentella/raspberry-dgc#34]
Ciao Luca ho risolto le mie problematiche riguardanti il programma e ora riesco a scansionare i qrcode. Ho solo due criticita' .
La prima e la velocita' per ogni scansione, ci vogliono circa 15 secondi per ottenere la rispsposta con il relativo risultato di valido o meno.
la seconda se apro il terminal su cameraclient e lancio lo script 'python3 cameraClient.py' dal terminal mi restituisce errore ma da un ide diverso tipo thonny python mi lancia il debug.
`sudo python3 cameraClient.py
Traceback (most recent call last):
  File "/home/pi/raspberry-dgc/cameraClient/cameraClient.py", line 1, in <module>
    from picamera.array import PiRGBArray
ModuleNotFoundError: No module named 'picamera'

`

**Comment by lucadentella** [comment]
Ciao Antonio, per la lentezza non saprei proprio dirti... il validatorServer sul mio Pi3 impiega meno di un secondo a rispondere.

Per l'errore python, stranissimo: la libreria picamera dovrebbe essere inclusa in qualsiasi distribuzione Raspbian senza necessità di installarla separatamente ... che immagine stai usando?

Nel caso prova a seguire le istruzioni sul sito ufficiale:
https://picamera.readthedocs.io/en/release-1.13/install.html

dove appunto dicono 

> If you are using the Raspbian distro, you probably have picamera installed by default
