### ISSUE TITLE
Error in Vaccination validation for cycle completed

### ISSUE THREAD

**Issue by AlessandroBagnoli** [lucadentella/raspberry-dgc#5]
Hello Luca, why are you only checking that the start date is greater than today date in the cycle completed part? You should also check that end date is greater than today:

startdate <= today <= enddate

Am I right?

REF:
https://github.com/lucadentella/raspberry-dgc/blob/e72bf4193d4b3ef6789e85745febea96aec82cc6/validatorServer/vaccination.js#L38

**Comment by lucadentella** [comment]
you're totally right! I forgot one line... fixing right now! thanks
