### ISSUE TITLE
Problem with new package

### ISSUE THREAD

**Issue by nikyred78** [lucadentella/raspberry-dgc#8]
**Hi Luca,
I Have some problem when I use the last package update.

When I stert this application app.js , return this message below:**

pi@raspberrypi:~/Downloads/raspberry-dgc-main/validatorServer $ node app.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node-fetch'
Require stack:
- /home/pi/Downloads/raspberry-dgc-main/validatorServer/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/Downloads/raspberry-dgc-main/validatorServer/app.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/Downloads/raspberry-dgc-main/validatorServer/app.js' ]
}
pi@raspberrypi:~/Downloads/raspberry-dgc-main/validatorServer $ 

If I start old version the application it's ok.

**Comment by lucadentella** [comment]
strange, I didn't change anything related to node-fetch.
I've just downloaded the repo in an empty folder and executed "npm install".
It worked, could you please try with a clean installation?

thanks

**Comment by nikyred78** [comment]
Hi,
I have to install new OS Raspbian clean o Can I to install only "npm install"?
Thanks

**Comment by lucadentella** [comment]
- download the repository in a new, empty folder
- in that folder, run "npm install"
- then run the validatorServer

**Comment by nikyred78** [comment]
Yes perfect.Thanks for your fast response.
After your procedure all function very well.

Then,
I Tried also the web interface with web chromium but return this error: NotReadableError : Could not start video source.
After this problem I have autorized the camera , but the problem remain.

**Comment by lucadentella** [comment]
Do not open the HTML page with a browser, you have to serve it using an http server (for example nginx or apache httpd).
Please test the library demo website to check the compatibility with your setup: https://blog.minhazav.dev/research/html5-qrcode.html

**Comment by nikyred78** [comment]
Do I have to point the raspberry from another position or can I open the page from the same raspberry?

**Comment by lucadentella** [comment]
First you have to install (if not already present) an http server on Raspberry (nginx, httpd...) and use it to publish the browserClient
Then change the following line in index.html with the URL where the validatorServer is running:
```
// validatorServer URL
const validatorServerURL = "http://raspberrypi.local:3000/";
```
You can now open the browserClient page from the Raspberry itself or with a different computer.

**Comment by nikyred78** [comment]
1 step: I installed nginx
2 step: I left this configuration because I want to open the page from the raspberry (// validatorServer URL
const validatorServerURL = "http: //raspberrypi.local: 3000 /";), or should I enter the raspberry ip? i think i have to leave local

then how should I open the page?
 Thank you for your support

**Comment by lucadentella** [comment]
2. it should work with raspberrypi.local
3. now open with a browser http://raspberrypi.local/browserClient and you should be able to use the web client

**Comment by nikyred78** [comment]
I copy the broswerClient folder inside the path / var / www / html /

after I launch the address "http: //raspberrypi.local/browserClient" from the web browser but it doesn't work

I tried to run this address "http: // localhost / browserClient", the page opens, then I authorize the camera pi but it gives me this error: NotReadableError: Could not start video source

**Comment by lucadentella** [comment]
Did you test the library demo? 
https://blog.minhazav.dev/research/html5-qrcode.html

Does it work?

**Comment by nikyred78** [comment]
yesterday this demo worked, today it didn't

**Comment by lucadentella** [comment]
unfortunately if the demo doesn't work for you, my example (that leverages the same library) won't too.
are you using the pi camera? Try to open the same page from a computer with an USB (or embedded) camera.

**Comment by nikyred78** [comment]
I have tried with the PC and it work. probable that I have to do the procedure again of installation os.
Thanks very much for your availability
